Prevent crash during ffi.load() when dlerror() returns NULL
Wohlhabend-Networks/LuaJIT pull request #13
Opened 2019-10-24 18:25 UTC by mcclure

The ffi.load() implementation assumes the string returned from dlerror() is non-NULL and immediately dereferences it. Per the standard definition of dlerror, this should always be safe, but we have observed dlerror() returning NULL on Android (Oculus Quest) anyway, which causes a crash. Patch issues a well-formed error instead of crashing.

I have submitted this in parallel to the normal luajit repo https://github.com/LuaJIT/LuaJIT/pull/522 but I'm not actually sure what the patch process is for luajit.

2019-10-24 19:23 UTC, Wohlstand requested changes

2019-10-24 19:23 UTC, Wohlstand commented on src/lj_clib.c
> +    if (err && *err == '/' && (e = strchr(err, ':')) &&
Can you add a comment with the note to explain why this `err` null check is here? Some sort of (you can rephraze it as you want):
```cpp
/* Per the standard definition of `dlerror`, this should always be safe, but we have 
 * observed dlerror() returning NULL on Android (Oculus Quest) anyway, which causes a crash. */
```
Also, optionally if possible, can you specify the version(s) of Android on which you have caught out for a crash?

2019-10-24 20:01 UTC, Wohlstand commented
Anyway, I think, I'll add this change myself, so, thank you for a workaround :fox_face:

2019-10-24 20:01 UTC, merged

2019-10-24 21:19 UTC, mcclure commented
Thanks! If you want to make note of it, the Android (Quest) device that returned the NULL gave me

```
$ adb shell getprop ro.build.version.release
7.1.1
$ adb shell getprop ro.build.version.sdk
25
```

I don't know if this is a universal behavior for Android 7/Nougat or if it is unique to this device.

2019-10-24 21:21 UTC, Wohlstand commented
Anyway, I will just add this as a note to understand for what platform this workaround targeted and where it was originally recognized. So, if it will happen again on someone's device, then, they are will see the source of a trouble as a soft error rather a destructive and painful crash :fox_face:

2019-10-24 21:27 UTC, mcclure commented
That makes sense! By the way, I think your most recent commit contains an error. It looks like you pasted the getprop stuff outside of the comment instead of inside of it. I don't think that will compile.

In my opinion it is enough to say that it was seen in Android 7.1.1 SDK 25. The getprop stuff is probably unnecessary to include.

Thanks

2019-10-24 21:31 UTC, Wohlstand commented
>  It looks like you pasted the getprop stuff outside of the comment instead of inside of it. I don't think that will compile.

Yeah, I have found this immediately, and it's just a stupid :man_facepalming: 
I have fixed it with a next commit. So, I'll better to squish this and force-push here then.

2019-10-24 21:46 UTC, Wohlstand commented
Done, so, now it should be correct :ok_hand: :fox_face:

2019-11-01 19:11 UTC, mcclure commented
@Wohlstand , I cherrypicked your commit into the Moonjit version of my PR, I understand this to be in line with the license on WohlSoft/LuaJIT but I just wanted to let you know

2019-11-01 19:43 UTC, Wohlstand commented
My repo is just a copy of the original with minor tweaks like enforcing UTF8 in file paths even on Windows (to avoid ANSI bullshit) and CMake build support I needed to don't deal with GNU Make limitations and build LuaJIT easily for everything. In all other cases, LuaJIT is matching to the mainstream. Yeah, the license is absolutely the same as the mainstream. 
Anyway, you could do that without any notice as the license is permissive, but thanks for a note and for one another "hello" :fox_face: :wink:

2019-11-01 19:59 UTC, Wohlstand commented
Oh, @mcclure , I have reviewed a bit the MoonJit project, and I am interested, what was changed in comparison to the original? I think you may also pick-up my UTF8 paths support (it replaces `fopen` and `freopen` with macro which is same everywhere except of Windows where are proxy functions are converting UTF8 into UTF16 for WinAPI `_wfopen` and `_wfreopen`, it can be enabled via macro, otherwise, on Windows, it will have default behavior with ANSI crap) and CMake build that simplifies dealing with different platforms :fox_face:  :wink:

2019-11-01 20:19 UTC, mcclure commented
@Wohlstand, MoonJIT is a fork of LuaJIT with many bug fixes not in trunk. A developer I work with says MoonJIT is likely to be "the most up to date LuaJIT" and that in their project it resulted in significant RAM gains.

I am with https://lovr.org (https://github.com/bjornbytes/lovr). We currently use WohlSoft LuaJIT because we require CMake for Android support. Neither LuaJIT trunk nor MoonScript has CMake.

I think it would be interesting to merge MoonScript together with the Wohlsoft changes. One way to do this would be if you created PRs for your Unicode and CMakeList changes and submitted them to MoonScript. Another possibility is I could create a Lovr organization LuaJIT which merges together Wohlsoft master with Moonscript master.